# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 20:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Numero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contatos.Pessoa')),
            ],
        ),
    ]
