# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 17:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0002_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Ferminino')], default='F', max_length=2),
        ),
        migrations.AlterField(
            model_name='numero',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numeros', to='contatos.Pessoa'),
        ),
    ]
