# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0003_auto_20160915_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='numero',
            name='tiponum',
            field=models.CharField(choices=[('Residencial', 'Residencial'), ('Movel', 'Movel')], default='Movel', max_length=20),
        ),
    ]
