# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0005_auto_20160915_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numero',
            name='numero',
            field=models.CharField(max_length=11),
        ),
    ]
